name: jong_jam
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.3.3

  loader_overlay: ^2.3.2
  shared_preferences: ^2.2.2
  go_router: ^11.1.2
  flutter_svg: ^2.0.7
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  http: ^1.1.0
  loading_indicator: ^3.1.1

  http_client:
    path: package/http_client
  sizer: ^2.0.15
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_crashlytics: ^3.3.7
  firebase_messaging: ^14.7.10
  cloud_firestore: ^4.14.0
  flutter_staggered_grid_view: ^0.7.0
  fl_chart: ^0.64.0
  showcaseview: ^2.0.3
  tutorial_coach_mark: ^1.2.11
  calendar_date_picker2: ^0.5.3
  firebase_storage: ^11.6.0
  flutter_local_notifications: ^16.3.0
  flutter_slidable: ^3.0.1
  animated_bottom_navigation_bar: ^1.3.2
  pinput: ^3.0.1
  firebase_app_check: ^0.2.1+8
  fluttertoast: ^8.2.4
  permission_handler: ^11.0.1
  flutter_gen_runner: ^5.2.0
  intl: any
  flutter_secure_storage: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  android: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  foreground_color: "#000000"
  adaptive_icon_foreground: "assets/images/logo.png"


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/svg/

  fonts:
    - family: Kantumruy Pro
      fonts:
        - asset: assets/fonts/KantumruyPro-Thin.ttf
          weight: 100
        - asset: assets/fonts/KantumruyPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/KantumruyPro-Light.ttf
          weight: 300
        - asset: assets/fonts/KantumruyPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/KantumruyPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/KantumruyPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/KantumruyPro-Bold.ttf
          weight: 700
