// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTgpN3tUFtIiy5IOomDUwzkoWkfVMXTJQ',
    appId: '1:1057522136718:web:2fe98c84eb02c7ee80bbdf',
    messagingSenderId: '1057522136718',
    projectId: 'flutter-note-app-86391',
    authDomain: 'flutter-note-app-86391.firebaseapp.com',
    storageBucket: 'flutter-note-app-86391.appspot.com',
    measurementId: 'G-Z7Y0WWWJ8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgxZjH9xgoTP2fQrfIqDxzokdKJt2fLn0',
    appId: '1:1057522136718:android:e20d6a20731e989780bbdf',
    messagingSenderId: '1057522136718',
    projectId: 'flutter-note-app-86391',
    storageBucket: 'flutter-note-app-86391.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLYCxopiriekbboasUaTKT1JG1oFySFvs',
    appId: '1:1057522136718:ios:0628c8ac01f0e28380bbdf',
    messagingSenderId: '1057522136718',
    projectId: 'flutter-note-app-86391',
    storageBucket: 'flutter-note-app-86391.appspot.com',
    iosBundleId: 'com.example.noteAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLYCxopiriekbboasUaTKT1JG1oFySFvs',
    appId: '1:1057522136718:ios:37ffbead909acdd080bbdf',
    messagingSenderId: '1057522136718',
    projectId: 'flutter-note-app-86391',
    storageBucket: 'flutter-note-app-86391.appspot.com',
    iosBundleId: 'com.example.noteAppFirebase.RunnerTests',
  );
}
